version: "3.2"

services:
  dev:
    container_name: basilisk-node
    image: paritytech/ci-linux:production
    working_dir: /basilisk-node
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/basilisk-node/.cargo
    volumes:
      - .:/basilisk-node
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/basilisk --dev --ws-external"
