[package]
authors = ['GalacticCouncil']
description = 'Pallet for asset registry management'
edition = '2018'
homepage = 'https://github.com/galacticcouncil/basilisk-node'
license = 'Apache 2.0'
name = 'pallet-asset-registry'
repository = 'https://github.com/galacticcouncil/basilisk-node'
version = '0.1.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-wasm-builder = {package = 'substrate-wasm-builder', version = '3.0.0'}

# alias "parity-scale-code" to "codec"
[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '2.0.0'

[dependencies]
primitive-types = {default-features = false, version = '0.8.0'}
serde = {features = ['derive'], optional = true, version = '1.0.101'}

# Local dependencies
primitives = {path = '../../primitives', default-features = false}

# Substrate dependencies
frame-support = {default-features = false, version = '3.0.0'}
frame-system = {default-features = false, version = '3.0.0'}
sp-core = {default-features = false, version = '3.0.0'}
sp-arithmetic = {default-features = false, version = '3.0.0'}
sp-runtime = {default-features = false, version = '3.0.0'}
sp-std = {default-features = false, version = '3.0.0'}
max-encoded-len = {default-features = false, version = '3.0.0'}

# Optionals
frame-system-benchmarking = {default-features = false, optional = true, version = '3.0.0'}
frame-benchmarking = {default-features = false, optional = true, version = '3.1.0'}
sp-api = {default-features = false, optional = true, version = '3.0.0'}

[dev-dependencies]
sp-io = {default-features = false, version = '3.0.0'}
polkadot-xcm = {package = "xcm", version = '0.9.8', default-features = false}

[features]
default = ['std']
runtime-benchmarks = [
  "frame-benchmarking",
  "frame-system/runtime-benchmarks",
  "frame-support/runtime-benchmarks",
]
std = [
  'serde/std',
  'codec/std',
  'frame-support/std',
  'frame-system/std',
  'sp-runtime/std',
  'sp-core/std',
  'sp-std/std',
  'primitives/std',
  'max-encoded-len/std',
  'sp-api/std',
  'frame-benchmarking/std'
]
