[package]
authors = ['GalacticCouncil']
build = 'build.rs'
description = 'Basilisk node'
edition = '2018'
homepage = 'https://github.com/galacticcouncil/Basilisk-node'
license = 'Apache 2.0'
name = 'basilisk'
repository = 'https://github.com/galacticcouncil/Basilisk-node'
version = '3.1.0'

[[bin]]
name = 'basilisk'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
hydra-dx-build-script-utils = {version = "1.0.0"}

[dependencies]
codec = {package = 'parity-scale-codec', version = '2.0.0'}
hex-literal = "0.3.1"
jsonrpc-core = '15.1.0'
log = '0.4.8'
serde = {version = '1.0.101', features = ['derive']}
serde_json = '1.0.64'
structopt = '0.3.8'

# local dependencies
basilisk-runtime = {path = '../runtime'}
pallet-xyk-rpc = {path="../pallets/xyk/rpc"}
primitives = {path = "../primitives"}

# Substrate dependencies
frame-benchmarking = '3.0.0'
frame-benchmarking-cli = {version = '3.0.0', optional = true}
pallet-transaction-payment-rpc = '3.0.0'
sc-basic-authorship = '0.9.0'
sc-chain-spec = '3.0.0'
sc-cli = {features = ['wasmtime'], version = '0.9.0'}
sc-client-api = '3.0.0'
sc-consensus = '0.9.0'
sc-consensus-aura = '0.9.0'
sc-executor = {features = ['wasmtime'], version = '0.9.0'}
sc-finality-grandpa = '0.9.0'
sc-keystore = '3.0.0'
sc-rpc = '3.0.0'
sc-rpc-api = '0.9.0'
sc-service = {features = ['wasmtime'], version = '0.9.0'}
sc-tracing = '3.0.0'
sc-telemetry = '3.0.0'
sc-transaction-pool = '3.0.0'
sp-api = '3.0.0'
sp-block-builder = '3.0.0'
sp-blockchain = '3.0.0'
sp-consensus = '0.9.0'
sp-consensus-aura = '0.9.0'
sp-core = '3.0.0'
sp-finality-grandpa = '3.0.0'
sp-inherents = '3.0.0'
sp-runtime = '3.0.0'
sp-timestamp = '3.0.0'
sp-transaction-pool = '3.0.0'
sp-trie = '3.0.0'
substrate-frame-rpc-system = '3.0.0'
sc-network = "0.9.0"
sp-keystore = "0.9.0"
sp-session = "3.0.0"
sp-offchain = "3.0.0"
substrate-prometheus-endpoint = "0.9.0"

# Cumulus dependencies
cumulus-client-cli = "0.1.0"
cumulus-client-collator = "0.1.0"
cumulus-client-consensus-aura = "0.1.0"
cumulus-client-consensus-relay-chain = "0.1.0"
cumulus-client-consensus-common = "0.1.0"
cumulus-client-network = "0.1.0"
cumulus-client-service = "0.1.0"
cumulus-primitives-core = "0.1.0"
cumulus-primitives-parachain-inherent = "0.1.0"

# Polkadot dependencies
polkadot-cli = {version="0.9.5"}
polkadot-parachain = {version="0.9.5"}
polkadot-primitives = {version="0.9.5"}
polkadot-service = {version="0.9.5"}
polkadot-test-service = {version="0.9.5"}

[features]
default = [
  "frame-benchmarking-cli",
]
runtime-benchmarks = [
  'basilisk-runtime/runtime-benchmarks',
  "frame-benchmarking-cli",
  'polkadot-service/runtime-benchmarks',
]

[dev-dependencies]
# Polkadot dependencies
polkadot-runtime-common = {version="0.9.5"}
polkadot-test-client = {version="0.9.5"}
polkadot-test-runtime = {version="0.9.5"}

# Substrate dependencies
pallet-sudo = {version="3.0.0"}
substrate-test-client = {version="2.0.1"}
substrate-test-runtime-client = {version="2.0.0"}
